### ISSUE TITLE
Add support for CSRF Protection token

### ISSUE THREAD

**Issue by jrasch** [Inedo/inedox-jenkins#23]
Jenkins now recommends adding a CSRF token as an HTTP header to all API requests as described here: https://wiki.jenkins.io/display/JENKINS/Remote+access+API#RemoteaccessAPI-CSRFProtection

Each operation that hits the Jenkins API should have a `CsrfProtectionEnabled` boolean property that defaults to `$JenkinsCsrfProtectionEnabled` variable function, which defaults to `true`, this way you could set a system variable with the same name to override this globally.

**Comment by BenLubar** [comment]
This appears to be the same as #18.
