### ISSUE TITLE
Unhandled exception: System.Runtime.Serialization.SerializationException

### ISSUE THREAD

**Issue by heyitsfranklin** [Inedo/inedox-jenkins#28]
I created a simple plan to execute a Jenkins build and import the build artifacts.

![screen](https://user-images.githubusercontent.com/11930733/51985938-012e8b80-2497-11e9-8748-f3eb956cd2fe.png)

The queue build step throws the following error when I attempt to execute this plan:
`Unhandled exception: System.Runtime.Serialization.SerializationException: Type 'Inedo.Extensions.Jenkins.Operations.QueueJenkinsBuildOperation' in Assembly 'Jenkins, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.`

Full stack trace: [exec-log-15.txt](https://github.com/Inedo/inedox-jenkins/files/2812811/exec-log-15.txt)

I've verified that this plan is setup correctly in BuildMaster because if I remove the Queue Jenkins Build step and just leave the Import Artifact step, BuildMaster successfully downloads the build artifacts from the latest build.

**Comment by heyitsfranklin** [comment]
After further investigation, it appears this is indeed a programatic error.

https://stackoverflow.com/questions/15707872/error-is-not-marked-as-serializable
https://stackoverflow.com/questions/11507819/serializationexception-type-is-not-marked-as-serializable-but-it-is?rq=1

Can someone please assist?

**Comment by gdivis** [comment]
This looks like a bug with the ProxyRequest argument, which unfortunately defaults to true. If you set it to false (it's under the Advanced tab), this should work, though the request to queue the build will always be made from the server BuildMaster is installed on in that case.

**Comment by heyitsfranklin** [comment]
@gdivis thanks that worked :D I'll leave this issue open then so the bug can be fixed.
